# .github/workflows/publish.yml
name: Quarto Publish

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # needed to push to gh-pages

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1) Install R on the runner
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.1'   # or 4.3.x/4.2.x if you prefer

      # 2) Install R package deps (knitr, rmarkdown, etc.)
      #    This will read your DESCRIPTION/renv.lock if present.
      - name: Install R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::knitr
            any::rmarkdown
            any::jsonlite
          needs: quarto

      # 3) Install Quarto CLI
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      # 4) Render + publish to gh-pages
      - name: Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
